import { PresetSourceCategory, PresetUnitType } from '../models/sizing.models';

export const PRESET_CATALOG_VERSION = '2026.02';

export interface PresetSource {
  id: string;
  category: PresetSourceCategory;
  vendor: string;
  product: string;
  unitType: PresetUnitType;
  defaultEpsPerUnit: number;
  epsRange: { min: number; max: number };
  avgEventBytes: number;
  notes: string;
  tags: string[];
}

export const PRESET_SOURCES_CATALOG: PresetSource[] = [
  {
    id: 'fortinet-fortigate-syslog',
    category: 'Firewall',
    vendor: 'Fortinet',
    product: 'FortiGate (syslog)',
    unitType: 'device',
    defaultEpsPerUnit: 20,
    epsRange: { min: 5, max: 80 },
    avgEventBytes: 350,
    notes: 'Depende del nivel de logging y las policies habilitadas.',
    tags: ['syslog', 'firewall'],
  },
  {
    id: 'cisco-asa-ftd',
    category: 'Firewall',
    vendor: 'Cisco',
    product: 'ASA/FTD',
    unitType: 'device',
    defaultEpsPerUnit: 15,
    epsRange: { min: 5, max: 60 },
    avgEventBytes: 380,
    notes: 'Alta variabilidad por ACL, VPN y eventos de denegacion.',
    tags: ['syslog', 'firewall'],
  },
  {
    id: 'paloalto-ngfw',
    category: 'Firewall',
    vendor: 'Palo Alto',
    product: 'NGFW',
    unitType: 'device',
    defaultEpsPerUnit: 25,
    epsRange: { min: 8, max: 120 },
    avgEventBytes: 420,
    notes: 'Sube rapido con threat logs, URL filtering y traffic logs.',
    tags: ['syslog', 'cef', 'firewall'],
  },
  {
    id: 'checkpoint-ngfw',
    category: 'Firewall',
    vendor: 'Check Point',
    product: 'Gateway',
    unitType: 'device',
    defaultEpsPerUnit: 18,
    epsRange: { min: 6, max: 90 },
    avgEventBytes: 400,
    notes: 'Depende de blades activos y granularidad de logs.',
    tags: ['syslog', 'firewall'],
  },
  {
    id: 'mikrotik-routeros-syslog',
    category: 'Router',
    vendor: 'Mikrotik',
    product: 'RouterOS (syslog)',
    unitType: 'device',
    defaultEpsPerUnit: 5,
    epsRange: { min: 1, max: 20 },
    avgEventBytes: 250,
    notes: 'Normalmente bajo salvo debug o alta actividad.',
    tags: ['syslog', 'router'],
  },
  {
    id: 'cisco-catalyst-syslog',
    category: 'Switch',
    vendor: 'Cisco',
    product: 'Catalyst (syslog)',
    unitType: 'device',
    defaultEpsPerUnit: 2,
    epsRange: { min: 0.5, max: 10 },
    avgEventBytes: 250,
    notes: 'Spanning tree, enlaces y cambios de estado dominan el volumen.',
    tags: ['syslog', 'switch'],
  },
  {
    id: 'aruba-hpe-syslog',
    category: 'Switch',
    vendor: 'Aruba/HPE',
    product: 'Switch (syslog)',
    unitType: 'device',
    defaultEpsPerUnit: 2,
    epsRange: { min: 0.5, max: 10 },
    avgEventBytes: 250,
    notes: 'Puede aumentar con eventos de autenticacion y roaming.',
    tags: ['syslog', 'switch'],
  },
  {
    id: 'fortigate-vpn-concentrator',
    category: 'VPN',
    vendor: 'Fortinet',
    product: 'FortiGate VPN',
    unitType: 'device',
    defaultEpsPerUnit: 10,
    epsRange: { min: 2, max: 40 },
    avgEventBytes: 350,
    notes: 'Crece en horarios punta y con MFA.',
    tags: ['syslog', 'vpn'],
  },
  {
    id: 'cisco-anyconnect-asa-vpn',
    category: 'VPN',
    vendor: 'Cisco',
    product: 'AnyConnect/ASA VPN',
    unitType: 'device',
    defaultEpsPerUnit: 8,
    epsRange: { min: 2, max: 30 },
    avgEventBytes: 350,
    notes: 'Conexiones, desconexiones y fallos de autenticacion dominan.',
    tags: ['syslog', 'vpn'],
  },
  {
    id: 'windows-server-security-log',
    category: 'Windows',
    vendor: 'Microsoft',
    product: 'Windows Server Security log',
    unitType: 'server',
    defaultEpsPerUnit: 3,
    epsRange: { min: 1, max: 15 },
    avgEventBytes: 700,
    notes: 'Aumenta con auditorias avanzadas y GPOs estrictas.',
    tags: ['winlog', 'security'],
  },
  {
    id: 'domain-controller-security-ad',
    category: 'Windows',
    vendor: 'Microsoft',
    product: 'Domain Controller (Security + AD)',
    unitType: 'server',
    defaultEpsPerUnit: 8,
    epsRange: { min: 3, max: 40 },
    avgEventBytes: 800,
    notes: 'Altamente sensible al numero de autenticaciones del dominio.',
    tags: ['winlog', 'ad'],
  },
  {
    id: 'linux-syslog-auth-audit',
    category: 'Linux',
    vendor: 'Linux',
    product: 'Syslog/auth/audit (moderado)',
    unitType: 'server',
    defaultEpsPerUnit: 1.5,
    epsRange: { min: 0.5, max: 8 },
    avgEventBytes: 450,
    notes: 'Auditd y autenticaciones elevan el volumen.',
    tags: ['syslog', 'linux', 'audit'],
  },
  {
    id: 'microsoft-defender-endpoint',
    category: 'EDR/XDR',
    vendor: 'Microsoft',
    product: 'Defender for Endpoint',
    unitType: 'agent',
    defaultEpsPerUnit: 0.4,
    epsRange: { min: 0.1, max: 2.0 },
    avgEventBytes: 1200,
    notes: 'Depende del plan y profundidad de telemetria.',
    tags: ['edr', 'json', 'cloud'],
  },
  {
    id: 'crowdstrike-falcon',
    category: 'EDR/XDR',
    vendor: 'CrowdStrike',
    product: 'Falcon',
    unitType: 'agent',
    defaultEpsPerUnit: 0.3,
    epsRange: { min: 0.1, max: 1.5 },
    avgEventBytes: 1400,
    notes: 'Puede subir con detecciones y hunting intensivo.',
    tags: ['edr', 'json', 'cloud'],
  },
  {
    id: 'sentinelone-agent',
    category: 'EDR/XDR',
    vendor: 'SentinelOne',
    product: 'Agent',
    unitType: 'agent',
    defaultEpsPerUnit: 0.35,
    epsRange: { min: 0.1, max: 1.8 },
    avgEventBytes: 1300,
    notes: 'Ajustar segun politicas de telemetria y rollback.',
    tags: ['edr', 'json', 'cloud'],
  },
  {
    id: 'sophos-central-xdr',
    category: 'EDR/XDR',
    vendor: 'Sophos',
    product: 'Central/XDR',
    unitType: 'user',
    defaultEpsPerUnit: 0.03,
    epsRange: { min: 0.01, max: 0.15 },
    avgEventBytes: 1000,
    notes: 'Modelado por usuario; depende de modulos activos y telemetria.',
    tags: ['xdr', 'cloud', 'user-based'],
  },
  {
    id: 'm365-unified-audit',
    category: 'Email',
    vendor: 'Microsoft',
    product: 'M365 Unified Audit',
    unitType: 'user',
    defaultEpsPerUnit: 0.02,
    epsRange: { min: 0.005, max: 0.1 },
    avgEventBytes: 1500,
    notes: 'Sube segun uso de Exchange, SharePoint y Teams.',
    tags: ['cloud', 'm365', 'audit'],
  },
  {
    id: 'azure-ad-signin',
    category: 'Cloud',
    vendor: 'Microsoft',
    product: 'Azure AD sign-in logs',
    unitType: 'user',
    defaultEpsPerUnit: 0.01,
    epsRange: { min: 0.002, max: 0.05 },
    avgEventBytes: 1200,
    notes: 'Ajustar por MFA, federacion y volumen de autenticaciones.',
    tags: ['cloud', 'identity', 'signin'],
  },
];
